DROP TABLE IF EXISTS `T_ACCOUNT`;
CREATE TABLE T_ACCOUNT(
	`ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
	`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`ACCOUNT_NAME` VARCHAR(50) NOT NULL COMMENT '账户名称',
	`PASSWORD` VARCHAR(50) NOT NULL COMMENT '账户密码',
	`USER_BASIC_ID` VARCHAR(50) COMMENT '关联用户',
	`MARK` VARCHAR(500) COMMENT '备注',
	PRIMARY KEY(`ID`),
	KEY idx_create_time(`CREATE_TIME`),
	KEY idx_account_name(`ACCOUNT_NAME`),
	KEY idx_user_basic_id(`USER_BASIC_ID`),
	CONSTRAINT `FK_T_USER_BASIC` FOREIGN KEY (`USER_BASIC_ID`) REFERENCES `T_USER_BASIC` (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='账户信息表';