DROP TABLE IF EXISTS `T_USER_BASIC`;
CREATE TABLE T_USER_BASIC(
	`ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
	`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`USER_NAME` VARCHAR(50) NOT NULL COMMENT '用户姓名',
	`SEX` bit(1) DEFAULT b'0' COMMENT '性别0.女；1.男',
	`BIRTHDAY` TIMESTAMP NOT NULL COMMENT '出生日期',
	`EMAIL` VARCHAR(100) COMMENT '邮箱',
	`ID_NUMBER` VARCHAR(30) COMMENT '身份证号码',
	`PHONE` VARCHAR(30) COMMENT  '电话',
	`MARK` VARCHAR(500) COMMENT '备注',
	PRIMARY KEY(`ID`),
	KEY IDX_CREATE_TIME(`CREATE_TIME`),
	KEY IDX_USER_NAME(`USER_NAME`),
	KEY IDX_SEX(`SEX`),
	KEY IDX_BIRTHDAY(`BIRTHDAY`),
	KEY IDX_EMAIL(`EMAIL`),
	KEY IDX_ID_NUMBER(`ID_NUMBER`),
	KEY IDX_PHONE(`PHONE`)
)ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='用户基本信息表';